name: Deploy to Maven Central

permissions: {}

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'corretto'
      - name: Deploy to Central Portal
        run: |
          echo "Publishing version: $PROJECT_VERSION"
          ./gradlew build
          ./gradlew publish
          ./gradlew jreleaserDeploy
        env:
          PROJECT_VERSION: ${{ github.event.release.tag_name }}
          JRELEASER_MAVENCENTRAL_STAGE: 'UPLOAD'
          JRELEASER_GPG_PUBLIC_KEY: |
            ${{ secrets.GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: |
            ${{ secrets.GPG_SECRET_KEY }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
